import PyPDF2
import io
from fpdf import FPDF


def extract_text_from_file(uploaded_file):
    """Extracts text from PDF/TXT so the AI can read your Nagaland documents."""
    text = ""
    try:
        if uploaded_file.name.endswith(".pdf"):
            reader = PyPDF2.PdfReader(io.BytesIO(uploaded_file.read()))
            for page in reader.pages:
                content = page.extract_text()
                if content:
                    text += content + "\n"
        elif uploaded_file.name.endswith(".txt"):
            text = uploaded_file.read().decode("utf-8")
        return text.strip()
    except Exception as e:
        return f"Error reading file: {e}"


def export_to_pdf(claim, verdict, reasoning, evidence):
    """Generates a formal report. Includes safety checks for empty data."""

    # --- SAFETY CHECK: Convert None to Strings to prevent 'NoneType' errors ---
    safe_claim = str(claim) if claim else "No claim provided"
    safe_verdict = str(verdict) if verdict else "ERROR/INCOMPLETE"
    safe_reasoning = str(reasoning) if reasoning else "No reasoning available"
    safe_evidence = str(
        evidence) if evidence else "No supporting evidence found"

    pdf = FPDF()
    pdf.add_page()

    # Title
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Nagaland Fake News Detection Report",
             ln=True, align='C')
    pdf.ln(10)

    # Claim & Verdict
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, txt=f"Claim:", ln=True)
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, txt=safe_claim)
    pdf.ln(2)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, txt=f"Status: {safe_verdict}", ln=True)
    pdf.ln(5)

    # Reasoning
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, txt="System Reasoning:", ln=True)
    pdf.set_font("Arial", size=11)
    pdf.multi_cell(0, 8, txt=safe_reasoning)
    pdf.ln(5)

    # Evidence (Safe slicing)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, txt="Detailed Evidence Summary:", ln=True)
    pdf.set_font("Arial", size=10)
    # Safe because we ensured it's a string
    pdf.multi_cell(0, 7, txt=safe_evidence[:2000])

    pdf.ln(10)
    # Branding
    pdf.set_font("Arial", 'I', 8)
    pdf.cell(0, 10, txt="Generated by Nagaland University Dept. of CSE Fact-Checker",
             ln=True, align='C')

    return pdf.output(dest='S').encode('latin-1')
